language: node_js

node_js:
  - '6'
  - '8'
  - '10'

sudo: required

services:
  - docker

before_install:
  - mkdir -p "$HOME/.yarn/bin"
  - curl -L -o "$HOME/.yarn/bin/yarn" https://github.com/yarnpkg/yarn/releases/download/v1.17.3/yarn-1.17.3.js
  - chmod +x "$HOME/.yarn/bin/yarn"
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn docker-boot

install:
  - yarn --ignore-engines

before_script:
  - yarn build-emscripten

script:
  - yarn lint
  - yarn test-fast
  - yarn check-prettier
  - yarn check-docs
  - yarn cover

after_success:
  - npm install -g coveralls
  - nyc report --reporter=text-lcov | coveralls
