language: node_js

node_js:
  - '6'
  - '8'
  - '10'

sudo: required

services:
  - docker

before_install:
  - yarn init-docker

before_script:
  - yarn build-emscripten
  - yarn dist-test

script:
  - yarn lint
  - yarn test-es6
  - yarn test-dist
  - yarn test-parity
  - yarn prettier && git diff --exit-code
  - yarn cover

after_success:
  - npm install -g coveralls
  - cat coverage/lcov.info | coveralls
