language: node_js

node_js:
  - '6'
  - '8'
  - '10'

sudo: required

services:
  - docker

before_install:
  - yarn docker-boot

before_script:
  - yarn build-emscripten

script:
  - yarn lint
  - yarn test-fast
  - yarn check-prettier
  - yarn check-docs
  - yarn cover

after_success:
  - npm install -g coveralls
  - nyc report --reporter=text-lcov | coveralls
